---
- name: Update /etc/apt/sources.list
  template:
    src: etc/apt/sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: Upgrade packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Install Nvidia required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - libgles2
    - libpangoft2-1.0-0
    - libxkbcommon0
    - libwayland-egl1
    - libwayland-cursor0
    - libunwind8
    - libasound2
    - libpixman-1-0
    - libjpeg-turbo8
    - libinput10
    - libcairo2
    - device-tree-compiler
    - iso-codes
    - libffi6
    - libncursesw5
    - libdrm-common
    - libdrm2
    - libegl-mesa0
    - libegl1
    - libegl1-mesa
    - libgtk-3-0
    - python2
    - python-is-python2
    - libgstreamer1.0-0
    - libgstreamer-plugins-bad1.0-0

- name: Install core packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - bash-completion
    - build-essential
    - btrfs-progs
    - cmake
    - curl
    - dnsutils
    - htop
    - iotop
    - isc-dhcp-client
    - iputils-ping
    - kmod
    - linux-firmware
    - locales
    - net-tools
    - netplan.io
    - pciutils
    - python3-dev
    - ssh
    - sudo
    - udev
    - unzip
    - usbutils
    - neovim
    - wpasupplicant

- name: Generate locales
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Enable services
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - ssh
    - systemd-networkd

- name: Update network conf
  template:
    src: etc/netplan/netcfg.yaml
    dest: /etc/netplan/netcfg.yaml
    owner: root
    group: root
    mode: 0644

- name: Create new user
  user:
    name: "{{ new_user.name }}"
    shell: "{{ new_user.shell }}"
    password: "{{ new_user.password | password_hash('sha512') }}"
    create_home: yes
    groups: sudo
    state: present

- name: Download pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: Install pip
  shell: python3 /tmp/get-pip.py --user
  become: yes
  become_user: "{{ new_user.name }}"


- name: Install docker dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    file: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Install Docker
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce
    - docker-ce-cli 
    - containerd.io

- name: Add user to docker group
  user:
    name: "{{ansible_user}}"
    group: docker


- name: Download docker-compose {{ docker_compose_version }}
  get_url:
    url : https://github.com/docker/compose-cli/releases/download/v2.0.0-beta.3/docker-compose-linux-arm64
    dest: ~/docker-compose
    mode: '+x'

- name: Check docker-compose exists
  stat: path=~/docker-compose
  register: docker_compose

- name: Move docker-compose to /usr/local/bin/docker-compose
  command: mv ~/docker-compose /usr/local/bin/docker-compose
  when: docker_compose.stat.exists
